version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - ./.docker/nginx/config/:/etc/nginx/conf.d/:ro
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - php
    ports:
      - "80:80"
  php:
    build:
      context: ./.docker/php
    working_dir: /var/www
    volumes:
      - .:/var/www
      - $HOME/.cache:/home/loudly/.cache
    environment:
      WORKDIR: "/var/www"
      MYUID: "${MYUID:-1000}"
      MYGID: "${MYGID:-1000}"
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        client_port=54321
        discover_client_host=1
        idekey=PHPSTORM
      XDEBUG_MODE: debug # off|debug|coverage
      XDEBUG_SESSION: PHPSTORM
      # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
      # Then PHPStorm will use the corresponding path mappings
      PHP_IDE_CONFIG: serverName=localhost
    extra_hosts:
      - host.docker.internal:host-gateway
    entrypoint: ./.docker/php/scripts/docker-entrypoint.sh
    command: php-fpm
    stdin_open: true
    tty: true
    ipc: host
  mariadb:
    image: mariadb:10.6.12
    environment:
      MYSQL_DATABASE: "loudly"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MARIADB_AUTO_UPGRADE: "true"
